
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  llama:
    image: ollama/ollama:latest   # Ollama local model image
    container_name: ollama
    ports:
      - "11434:11434"            # Ollama CLI server port
    volumes:
      - ollama_data:/root/.ollama   # Ollama data хадгалах
    environment:
      - OLLAMA_API_KEY=local        # Local mode ашиглах

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    depends_on:
      - qdrant
    environment:
      QDRANT_URL: "http://qdrant:6333"      
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    env_file: .env
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:8000/ask"
    ports:
      - "5000:5000"

volumes:
  qdrant_storage:
  ollama_data:

  

